Name:           ros-kinetic-feed-the-troll
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS feed_the_troll package

Group:          Development/Libraries
License:        MIT
URL:            http://www.ros.org/wiki/feed_the_troll
Source0:        %{name}-%{version}.tar.gz

Requires:       python-termcolor
Requires:       ros-kinetic-dynamic-reconfigure
Requires:       ros-kinetic-feed-the-troll-msgs
Requires:       ros-kinetic-rocon-console
Requires:       ros-kinetic-rocon-python-utils
Requires:       ros-kinetic-rosgraph
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-unique-id
Requires:       ros-kinetic-uuid-msgs
BuildRequires:  python-termcolor
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-dynamic-reconfigure
BuildRequires:  ros-kinetic-feed-the-troll-msgs
BuildRequires:  ros-kinetic-rocon-console
BuildRequires:  ros-kinetic-rocon-python-utils
BuildRequires:  ros-kinetic-rosgraph
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-rostest
BuildRequires:  ros-kinetic-unique-id
BuildRequires:  ros-kinetic-uuid-msgs

%description
Mechanisms for loading a ros node at runtime.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Jan 26 2017 Daniel Stonier <d.stonier@gmail.com> - 0.1.1-0
- Autogenerated by Bloom

